version: "3.0"
services:
  client:
    build: ./client
    restart: always
    ports:
      - 80:80
  backend:
    build: ./backend
    restart: always
    ports:
      - 3000:3000
    links:
      - "db:database"
  db:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017